### ISSUE TITLE
Error on bookinstance_delete_post

### ISSUE THREAD

**Issue by MadRiver44** [mdn/express-locallibrary-tutorial#1]
Hi, 
I keep getting an error when I try to delete a bookinstance, specifically:

**___*Cast to ObjectId failed for value "bookinstance._id" at path "_id" for model "BookInstance"*___.**

I checked my bookinstance model, I went through my bookinstance controller for delete_get and delete_post. Then I compared to your code and I can't seem to spot a difference. Are you getting this error as well?

Here is a link to my [bookinstance controller](https://github.com/MadRiver44/LibraryApp/blob/master/controllers/bookinstanceController.js)

Update: I copied your code directly (bookinstance model and bookinstance controller) and got the same error

**Comment by hamishwillee** [comment]
I don't get this error. If you try with the whole project does it work?

**Comment by MadRiver44** [comment]
i found that when i pass req.params.id

    BookInstance.findByIdAndRemove(req.params.id, function deleteBookInstance(err) {
    ....

it works, i updated my [repo](https://github.com/MadRiver44/LibraryApp/blob/master/controllers/bookinstanceController.js) so you can see

**Comment by hamishwillee** [comment]
This is a bug in your view code [here](https://github.com/MadRiver44/LibraryApp/blob/master/views/bookinstance_delete.pug#L31):
```
input#id.form-control(type='hidden', name='id' required='true' value='bookinstance._id')
```
What this is supposed to do is create a hidden form input with a value containing the book instance id. Because this is in the form, it is read by the controller body code. The problem is that you're passing this value a static string ``value='bookinstance._id')`` not the id itself. So to get this to work you'd have to do:
``value=bookinstance._id)``

This is as documented in the [tutorial here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms#View_5).

**Comment by MadRiver44** [comment]
AHHHH!, thanks....I knew it was me. Appreciate the help!
