### ISSUE TITLE
Please review naming conventions

### ISSUE THREAD

**Issue by LondonPhil** [mdn/express-locallibrary-tutorial#67]
This is not a coding issue - it more to do with making the otherwise excellent tutorial easier to comprehend.  As someone new to Javascript I cannot easily understand the coding examples when you use the same word to describe many similar things.  For example you use '**author**' to be both a file name and a document name - so by using 'author' in the the following code it really does not illustrate when to use each instance of 'author':

 **_for author in authors
    if book
      option(value=author._id selected=(author._id.toString()==book.author._id.toString() ? 'selected' : false) ) #{author.name}
    else
      option(value=author._id) #{author.name}_**

If you had used 'people' for one and 'author_id'  for the other it would make understanding so much easier.  The same goes for 'genre', which can also used to mean two completely different things in the same command line.

I have had similar difficulties when variables/functions are given names that could easily be Javascript commands - as it is not always apparent what words/terms you are demonstrating, and which ones are simply made up. 

Otherwise I have found this tutorial very useful and thank you for giving up your time to produce it.

**Comment by hamishwillee** [comment]
@LondonPhil Thank you.

The code you are pointing to is https://github.com/mdn/express-locallibrary-tutorial/blob/master/views/book_form.pug#L14-L18 , which is documented in https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form
```
        for author in authors
          if book
            option(value=author._id selected=(author._id.toString()==book.author._id.toString() ? 'selected' : false) ) #{author.name}
          else
            option(value=author._id) #{author.name}
```
The variable `authors` is a variable that is passed in from code. It is a list of `author` variables. I could have written like this:
```
        for person in authors
          if book
            option(value=person._id selected=(person._id.toString()==book.author._id.toString() ? 'selected' : false) ) #{person.name}
          else
            option(value=person._id) #{person.name}
```

Firstly I can't name `people` for one and `author_id` for another because `_id` is a property of the object.  So it is either `author` and `author._id` OR `people` and `people._id`.

If I do change author to people as above it is not really any less confusing; though I guess now you can see that `book.author._id.toString()` is a different variable than `author._id.toString()`. Also to me it seems logical that a list of author objects will be called author**s**. 

Respectfully I agree with your sentiment that naming is hard and that this may be hard to read. However it is consistent, and I do not think that it is worth the effort of changing.
